/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author ASUS
 */
public class ADILA_06111840000092_TUGAS2 extends javax.swing.JDialog {
    /**
     * Creates new form TugasAsis
     */
    public ADILA_06111840000092_TUGAS2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSoal = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPreviewSoal = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jNilaiA = new javax.swing.JTextField();
        jNilaiN = new javax.swing.JTextField();
        jNilaiX = new javax.swing.JTextField();
        jHitung = new javax.swing.JButton();
        jReset = new javax.swing.JButton();
        jKeluar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jHasil = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jKeterangan = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));

        jSoal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Salah Satu Soal", "Soal 2", "Soal 4", "Soal 5" }));
        jSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSoalActionPerformed(evt);
            }
        });

        jPreviewSoal.setColumns(20);
        jPreviewSoal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPreviewSoal.setRows(5);
        jScrollPane1.setViewportView(jPreviewSoal);

        jLabel1.setText("Masukkan Nilai a");

        jLabel2.setText("Masukkan Nilai n");

        jLabel3.setText("Masukkkan Nilai x");

        jHitung.setText("Hitung");
        jHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jHitungActionPerformed(evt);
            }
        });

        jReset.setText("Reset");
        jReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetActionPerformed(evt);
            }
        });

        jKeluar.setText("Keluar");
        jKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jKeluarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nilai f(x)");

        jHasil.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jKeterangan.setColumns(20);
        jKeterangan.setRows(5);
        jScrollPane2.setViewportView(jKeterangan);

        jLabel5.setFont(new java.awt.Font("AR BONNIE", 0, 36)); // NOI18N
        jLabel5.setText("TUGAS ASISTENSI ALGORITMA PEMOGRAMAN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel5))
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(267, 267, 267)
                .addComponent(jKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jHitung))
                            .addComponent(jLabel3))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNilaiX, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jReset))
                        .addGap(133, 133, 133)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSoal, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(76, 76, 76)
                                .addComponent(jNilaiA, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(76, 76, 76)
                                .addComponent(jNilaiN, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(127, 127, 127)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jSoal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel1))
                            .addComponent(jNilaiA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel2))
                            .addComponent(jNilaiN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jHitung))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jNilaiX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addComponent(jReset))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel4))
                    .addComponent(jHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jKeluar))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetActionPerformed
       jNilaiA.setText(null);
       jNilaiN.setText(null);
       jNilaiX.setText(null);
       jHasil.setText(null);
       jPreviewSoal.setText(null);
    }//GEN-LAST:event_jResetActionPerformed

    private void jKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jKeluarActionPerformed
      this.dispose();
    }//GEN-LAST:event_jKeluarActionPerformed

    private void jSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSoalActionPerformed
      String soal = (String)jSoal.getSelectedItem();
      if (soal == "Soal 2"){
          String soal2 = "f(x) = sin (2x)";
          jPreviewSoal.setText(String.valueOf(soal2));
          jKeterangan.setText("Masukkan a bilangan positif, n bilangan bulat positif, dan x bilangan positif");
      } else if (soal == "Soal 4"){
          String soal4 = "f(x) = ln (-x)";
          jPreviewSoal.setText(String.valueOf(soal4));
          jKeterangan.setText("Masukkan a bilangan negatif, n bilangan bulat positif, dan x bilangan negatif");
      }else if (soal == "Soal 5"){
          String soal5 = "f(x) = x / 1 - x";
          jPreviewSoal.setText(String.valueOf(soal5));
          jKeterangan.setText("Masukkan a bilangan real, n bilangan bulat positif, dan x<1");
      }
    }//GEN-LAST:event_jSoalActionPerformed

    private void jHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jHitungActionPerformed
      int n, a, x;
      n=(int) Double.parseDouble(jNilaiN.getText());
      a=(int) Double.parseDouble(jNilaiA.getText());
      x=(int) Double.parseDouble(jNilaiX.getText());
      
      if (n==0){
            jHasil.setText("Nilai n tidak boleh 0");
            
      }else{
      String soal = (String)jSoal.getSelectedItem();
   
      //Perhitungan Soal 2
      if (soal=="Soal 2"){
        jHasil.setText(String.valueOf(Soal2(a,n,x)));
         
    }else if (soal=="Soal 4"){ //Perhitungan Soal 4
        
        jHasil.setText(String.valueOf(Soal4(a,n,x)));
        
      }else if (soal=="Soal 5"){ //Perhitungan Soal 5
        
        jHasil.setText(String.valueOf(Soal5(a,n,x)));
        
    }else{
          System.out.println("Input tidak terdeteksi karena tidak sesuai dengan ketentuan syarat yang ada");
      }
      }
    
    }//GEN-LAST:event_jHitungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADILA_06111840000092_TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADILA_06111840000092_TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADILA_06111840000092_TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADILA_06111840000092_TUGAS2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ADILA_06111840000092_TUGAS2 dialog = new ADILA_06111840000092_TUGAS2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jHasil;
    private javax.swing.JButton jHitung;
    private javax.swing.JButton jKeluar;
    private javax.swing.JTextArea jKeterangan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jNilaiA;
    private javax.swing.JTextField jNilaiN;
    private javax.swing.JTextField jNilaiX;
    private javax.swing.JTextArea jPreviewSoal;
    private javax.swing.JButton jReset;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jSoal;
    // End of variables declaration//GEN-END:variables

  
    
    //Perhitungan Soal 2
    public static double Soal2(double a,double n, double x){
        double [] p = new double[10001];
        double es = 0.5*Math.pow(10,2-n);
        double q=0, c=0,s=0;
        p[0] = Math.sin(Math.toRadians(2*x));
         for (int i=0;i<=10000;i++){
            double c1 = (Math.pow(-1,i+2))*(Math.pow(2,(2*i)+1));
            double c2 = (Math.cos(Math.toRadians((2*x)*(Math.pow(x-a,i+1)))));
            double s1 = ((Math.pow(-1,i+1))*(Math.pow(2,(2*i)+2)));
            double s2 = (Math.sin(Math.toRadians((2*x)*(Math.pow(x-a,i+2)))));
            
                if(i%2==0){
                    s = (s1*s2)/(faktorial(i));
                }else{
                    c = (c1*c2)/(faktorial(i));
                }
            
            
            p[i] = p[0]+c+s;
            double ea = ((p[i]-p[i-1])/p[i])*100;
            if (Math.abs(ea)<(es)){
                 q += p[i];
                 System.out.println(i);
                 break;
            }
          }
          double Hasil2 = q;
          return Hasil2;
    }
    
    //Menghitung Nilai Faktorial
    public static int faktorial(int n){
        int f = 1;
        for(int i=1;i<=n;i++){
            f=f*i;
        }
        return f;
    }
    
    //Perhitungan Soal 4
    public static double Soal4(double a,double n, double x){
        double [] f = new double[10001];
        double es = 0.5*Math.pow(10,2-n);
        f[0] = Math.log(-x);
        double q=0;
        
        for (int i=1;i<10000;i++){
            f[i]=f[0]+((Math.pow(x-a,i)*Math.pow(-1, i))/(Math.pow(x,i))*i);
            double ea = ((f[i]-f[i-1])/f[i])*100;
            if (Math.abs(ea)<(es)){
                 q += f[i];
                 System.out.println(i);
                 break;
            }
        }
        double Hasil4 = q;
        return Hasil4;
    }
     
    //Perhitungan Soal 5
    public static double Soal5(double a,double n, double x){
        double [] f = new double[10001];
        double es = 0.5*Math.pow(10,2-n);
        f[0]= x/(1-x);
        double q=0;
        
        for (int i=1;i<10000;i++){
            f[i]= f[0]+((Math.pow(x-a,i))*(Math.pow(-1,i))/(Math.pow(1-x,i+1)));
            double ea = ((f[i]-f[i-1])/f[i])*100;
            if (Math.abs(ea)<(es)){
                 q += f[i];
                 System.out.println(i);
                 break;
            }
        }
        double Hasil5 = q;
        return Hasil5;
    }
}